### ISSUE TITLE
One-liner json files inconvenient

### ISSUE THREAD

**Issue by vimuel** [ukc-co663/depsolver#3]
It is extremely inconvenient for editors, vcs and wetware to have huge one-liner json files.

I have `fold`ed mine locally, and would suggest that we do the same here.

I am happy to open a pull-request, or you can just run something like:

```
fold -w 80 -s
```

**Comment by rgrig** [comment]
I think it might be better if you avoid reading these files and, instead, write your own small and tricky tests. The seen tests are not really meant to be read by humans but by machine.

If you do a PR, though, please do some proper indenting, not just spitting on spaces.

**Comment by vimuel** [comment]
Ah, fine. That makes sense.
